language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - spark-submit bitcointrading.py "input/dataset_one.csv" "input/dataset_two.csv" "United Kingdom,Netherlands" "client_data"

after_success:
  - python readlogfile.py



