language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

#branches:
#  only:
#    - master





#jobs:
#  - include:
#      - stages:
#          - compile
#          - test
#              - script

#- deploy

script:
#  - python helloworld.py
#  - spark-submit abnamro.py 'input/dataset_one.csv'
  - print("Integration between git and travis ci")



